services:
  - type: web
    name: lavalust
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_DRIVER
        value: mysql
      - key: DB_HOST
        value: localhost
      - key: DB_PORT
        sync: false
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_CHARSET
        value: utf8mb4
      - key: DB_SSL_CA
        sync: false